:base-url = http://localhost:3000

# GET /dishes
GET :base-url/dishes

# POST /dishes
POST :base-url/dishes
Content-Type: application/json

{
  "name": "balakas",
  "description": "best balakas in the world"
}

# PUT /dishes
PUT :base-url/dishes
Content-Type: application/json

{
  "name": "shit",
  "description": "shit"
}

# DELETE /dishes
DELETE :base-url/dishes

:dishId = 5a9e7d7d2e20ba382fa1fdf4
# GET /dishes/:dishId
GET :base-url/dishes/:dishId

# POST /dishes/:dishId
POST :base-url/dishes/:dishId
Content-Type: application/json

{
  "name": "shit",
  "description": "shit"
}

# PUT /dishes/:dishId
PUT :base-url/dishes/:dishId
Content-Type: application/json

{
  "description": "updated balakas"
}

# DELETE /dishes/:dishId
DELETE :base-url/dishes/:dishId